services:
  api:
    build: ./finpro-api
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./finpro-api:/app
      - /app/node_modules
    restart: unless-stopped

  web:
    build: ./finpro-web
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    volumes:
      - ./finpro-web:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped
